CREATE TABLE STUDENT(
          SNO INT              ,
          NAME VARCHAR(20)     , 
          MARKS INT            ,
          DEPT CHAR(25)
    );

ALTER TABLE STUDENT 
ADD COLUMN AGE INT;

ALTER TABLE STUDENT
MODIFY COLUMN DEPT CHAR(20);

ALTER TABLE STUDENT 
DROP COLUMN MARKS;

ALTER TABLE STUDENT
RENAME TO STUDENTS;

INSERT INTO STUDENTS 
VALUES(39,'LINCY','CSE', 21);

TRUNCATE STUDENTS;

DROP TABLE STUDENTS;
